services:
  - type: web
    name: virtual-tryon
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: U2NET_HOME
        value: /tmp/u2net
      - key: PYTHON_VERSION
        value: 3.11.9
